"use client";

import { icons, Folder, type LucideProps } from "lucide-react";

// Default icon when a project has no icon set or names an unknown one.
export const DEFAULT_PROJECT_ICON = "Folder";

/** A random icon name from the curated set, for instantly-created projects. */
export function randomProjectIcon(): string {
  return PROJECT_ICON_NAMES[Math.floor(Math.random() * PROJECT_ICON_NAMES.length)];
}

/**
 * Renders a Lucide icon by its PascalCase name (e.g. "Folder", "BookOpen").
 * Falls back to a folder icon for unknown / missing names.
 */
export function LucideIcon({
  iconName,
  ...props
}: { iconName?: string | null } & LucideProps) {
  const Icon = (iconName && icons[iconName as keyof typeof icons]) || Folder;
  return <Icon {...props} />;
}

// A curated, search-friendly set of icons for the project picker. cmdk keeps
// every item mounted, so a focused list (not all ~1700 Lucide icons) keeps the
// popover snappy while still covering common note/course/subject themes.
// Deduped so React never sees a repeated key.
export const PROJECT_ICON_NAMES: string[] = Array.from(new Set<string>([
  "Folder",
  "FolderOpen",
  "FolderGit2",
  "Files",
  "FileText",
  "Notebook",
  "NotebookPen",
  "BookOpen",
  "BookMarked",
  "Book",
  "Library",
  "GraduationCap",
  "School",
  "Backpack",
  "PencilRuler",
  "Pencil",
  "PenTool",
  "Highlighter",
  "Brain",
  "Lightbulb",
  "Sparkles",
  "Star",
  "Heart",
  "Bookmark",
  "Tag",
  "Tags",
  "Pin",
  "Flag",
  "Target",
  "Trophy",
  "Award",
  "Medal",
  "Rocket",
  "Compass",
  "Map",
  "MapPin",
  "Globe",
  "Languages",
  "Calculator",
  "Sigma",
  "Pi",
  "Binary",
  "FunctionSquare",
  "Atom",
  "FlaskConical",
  "TestTube",
  "Microscope",
  "Dna",
  "Beaker",
  "Magnet",
  "Orbit",
  "Telescope",
  "Leaf",
  "Sprout",
  "TreePine",
  "Bug",
  "Bird",
  "Cat",
  "Dog",
  "Code",
  "Code2",
  "Terminal",
  "Cpu",
  "Database",
  "Server",
  "Cloud",
  "Bot",
  "CircuitBoard",
  "Keyboard",
  "Monitor",
  "Smartphone",
  "Briefcase",
  "Building2",
  "Landmark",
  "Scale",
  "Gavel",
  "TrendingUp",
  "LineChart",
  "BarChart3",
  "PieChart",
  "DollarSign",
  "CreditCard",
  "Coins",
  "Wallet",
  "Palette",
  "Brush",
  "Image",
  "Camera",
  "Film",
  "Music",
  "Music2",
  "Mic",
  "Headphones",
  "Guitar",
  "Piano",
  "Drama",
  "Clapperboard",
  "Gamepad2",
  "Dumbbell",
  "Bike",
  "Trophy",
  "Activity",
  "HeartPulse",
  "Stethoscope",
  "Pill",
  "Apple",
  "Coffee",
  "Utensils",
  "ChefHat",
  "Pizza",
  "Plane",
  "Car",
  "Train",
  "Ship",
  "Mountain",
  "Tent",
  "Sun",
  "Moon",
  "Star",
  "Cloud",
  "Umbrella",
  "Snowflake",
  "Flame",
  "Zap",
  "Clock",
  "Calendar",
  "CalendarDays",
  "AlarmClock",
  "Timer",
  "Hourglass",
  "ListChecks",
  "ClipboardList",
  "CheckSquare",
  "Inbox",
  "Archive",
  "Box",
  "Package",
  "Layers",
  "Grid2x2",
  "LayoutGrid",
  "Hash",
  "AtSign",
  "Puzzle",
  "Wrench",
  "Settings",
  "Cog",
  "Hammer",
  "Shield",
  "Key",
  "Lock",
  "Anchor",
  "Feather",
  "Quote",
  "MessageSquare",
  "Users",
  "User",
  "Smile",
]));
