import type { AnvilTemplate, TemplatePreview } from "@/types/template";
import { getApiBaseUrl } from "@/lib/api";

// Preview assets are pre-generated by the API and served statically at
// /static/template-previews/{id}/. The web app derives the URLs from the
// template id by convention, so the templates API doesn't need to know about
// previews. An explicit `template.preview` (if ever provided) wins.
export function getTemplatePreview(template: AnvilTemplate): TemplatePreview {
  if (template.preview) {
    return template.preview;
  }
  const base = `${getApiBaseUrl()}/static/template-previews/${template.id}`;
  return {
    pdfUrl: `${base}/preview.pdf`,
    thumbnailUrl: `${base}/thumbnail.png`,
    manifestUrl: `${base}/manifest.json`,
  };
}
