import type { JSONContent } from "@tiptap/core";
import {
  ANVIL_NOTE_CALLOUT_KINDS,
  ANVIL_NOTE_QUESTION_KINDS,
  ANVIL_NOTE_WRITTEN_MODES,
  type AnvilNoteCalloutKindV1,
  type AnvilNoteQuestionKindV1,
  type AnvilNoteWrittenModeV1,
} from "@anvilnote/ai-writer/document";
import { AiSnapshotConversionError } from "./ai-snapshot-errors";
import {
  localRefAttr,
  type SnapshotConversionContext,
  type TiptapConversionContext,
} from "./core-node-converters";

// Tiptap JSON <-> AI document v2 mapping for the "structured" node family:
// callout/proof/question hierarchy/table hierarchy/footnote hierarchy, PLUS
// the reference-style inline nodes (crossRef/footnoteReference/
// questionBlank/inlineBlank) — folded into this same file rather than a 4th
// module (ai-writer's own reference-nodes.ts is separate from
// structured-nodes.ts, but on the web side these are all tightly coupled:
// crossRef targets heading/blockMath/table/questionItem, footnoteReference
// targets footnote — splitting them out further didn't earn its own file).
//
// targetRef/localRef round-tripping — see core-node-converters.ts's own
// header comment for the general policy (direct, reversible id<->localRef
// passthrough). The concrete real-editor attribute names below were
// re-verified directly against source, not assumed from a prior task's
// findings for a different repo:
//   - crossRef (cross-ref.ts):      attrs.targetId (+ derived resolvedKind/
//                                   resolvedValue/broken — recomputed live
//                                   by CrossRefTargetIds's resolver plugin,
//                                   stripped here, never forwarded).
//   - questionBlank (question-blank.ts): attrs.targetId (+ derived
//                                   resolvedValue/broken, same treatment).
//   - footnoteReference (tiptap-footnotes' reference.ts): the real Tiptap
//                                   ATTRS KEY is the literal string
//                                   "data-id" (bracket access required,
//                                   e.g. node.attrs["data-id"] — not
//                                   `dataId` and not a separate `id`),
//                                   plus a derived `referenceNumber`
//                                   (recomputed every transaction by
//                                   footnoteRules' appendTransaction,
//                                   stripped here) and fixed/cosmetic
//                                   `class`/`href` (never round-tripped).
//   - footnote (tiptap-footnotes' footnote.ts): TWO real attrs share the
//                                   name "id" conceptually but are
//                                   different fields — `id` itself is a
//                                   DERIVED "fn:N" display label
//                                   (regenerated by footnoteRules on every
//                                   transaction that touches references),
//                                   while the STABLE link back to its
//                                   footnoteReference is the separate
//                                   `"data-id"` attr (also bracket-access,
//                                   `isRequired: true`). This module's
//                                   localRef comes from `"data-id"`, never
//                                   from `id`.
export function attrsOf(node: JSONContent): Record<string, unknown> {
  return node.attrs ?? {};
}

function requiredString(value: unknown, field: string): string {
  if (typeof value === "string" && value.length > 0) return value;
  throw new AiSnapshotConversionError(`${field} is required and must be a non-empty string.`);
}

function calloutKind(value: unknown): AnvilNoteCalloutKindV1 {
  if (typeof value === "string" && (ANVIL_NOTE_CALLOUT_KINDS as readonly string[]).includes(value)) {
    return value as AnvilNoteCalloutKindV1;
  }
  throw new AiSnapshotConversionError(`Unknown callout kind: ${String(value)}`);
}

function questionKind(value: unknown): AnvilNoteQuestionKindV1 {
  if (typeof value === "string" && (ANVIL_NOTE_QUESTION_KINDS as readonly string[]).includes(value)) {
    return value as AnvilNoteQuestionKindV1;
  }
  throw new AiSnapshotConversionError(`Unknown question kind: ${String(value)}`);
}

function writtenMode(value: unknown): AnvilNoteWrittenModeV1 {
  if (typeof value === "string" && (ANVIL_NOTE_WRITTEN_MODES as readonly string[]).includes(value)) {
    return value as AnvilNoteWrittenModeV1;
  }
  throw new AiSnapshotConversionError(`Unknown written mode: ${String(value)}`);
}

function requiredNumber(value: unknown, field: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new AiSnapshotConversionError(`${field} must be a finite number.`);
  }
  return value;
}

// Task 24.3 finding: every field below is now unconditionally present
// (`null` fallback), matching anvilnote-api's own
// persisted-document-node-mappers.ts `mapPersistedNodeToV2` exactly — see
// core-node-converters.ts's header comment for the full rationale (a
// baseDocumentHash parity bug, confirmed empirically). The OLD code
// conditionally omitted colwidth/fill/stroke/inset/breakable/verticalAlign
// whenever a cell used no custom styling — the overwhelmingly common case —
// which desynced this hash from the server's for nearly every real table.
function cellAttrsToSnapshot(node: JSONContent): Record<string, unknown> {
  const values = attrsOf(node);
  return {
    colspan: Number(values.colspan ?? 1),
    rowspan: Number(values.rowspan ?? 1),
    colwidth: Array.isArray(values.colwidth) ? (values.colwidth as number[]) : null,
    fill: typeof values.fill === "string" ? values.fill : null,
    stroke: typeof values.stroke === "string" ? values.stroke : null,
    inset: typeof values.inset === "string" ? values.inset : null,
    breakable: typeof values.breakable === "boolean" ? values.breakable : null,
    verticalAlign: typeof values.verticalAlign === "string" ? values.verticalAlign : null,
  };
}

function cellAttrsFromSnapshot(values: Record<string, unknown>): Record<string, unknown> {
  return {
    colspan: typeof values.colspan === "number" ? values.colspan : 1,
    rowspan: typeof values.rowspan === "number" ? values.rowspan : 1,
    colwidth: values.colwidth ?? null,
    fill: typeof values.fill === "string" ? values.fill : null,
    stroke: typeof values.stroke === "string" ? values.stroke : null,
    inset: typeof values.inset === "string" ? values.inset : null,
    breakable: typeof values.breakable === "boolean" ? values.breakable : null,
    verticalAlign: typeof values.verticalAlign === "string" ? values.verticalAlign : null,
  };
}

// --- Forward: Tiptap -> v2-shaped JSON ------------------------------------

export function structuredNodeToSnapshot(
  node: JSONContent,
  ctx: SnapshotConversionContext,
): JSONContent | undefined {
  const content = node.content ?? [];
  const values = attrsOf(node);

  switch (node.type) {
    case "callout": {
      const title = typeof values.title === "string" ? values.title.trim() : "";
      return {
        type: "callout",
        attrs: { kind: calloutKind(values.kind), title: title.length > 0 ? title : null },
        content: content.map((child) => ctx.block(child)),
      };
    }
    case "proof":
      return { type: "proof", content: content.map((child) => ctx.block(child)) };
    case "question":
      return { type: "question", content: content.map((child) => ctx.block(child)) };
    case "questionItem": {
      if (values.stashedChoiceJSON !== undefined && values.stashedChoiceJSON !== null) {
        throw new AiSnapshotConversionError(
          "A hidden stashed choice cannot be forwarded to Smart Mode without data loss.",
        );
      }
      return {
        type: "questionItem",
        attrs: {
          kind: questionKind(values.kind),
          writtenMode: writtenMode(values.writtenMode),
          writtenLines: requiredNumber(values.writtenLines, "questionItem.writtenLines"),
          writtenHeightPercent: requiredNumber(
            values.writtenHeightPercent,
            "questionItem.writtenHeightPercent",
          ),
          writtenHeightCm:
            values.writtenHeightCm === null || values.writtenHeightCm === undefined
              ? null
              : requiredNumber(values.writtenHeightCm, "questionItem.writtenHeightCm"),
          multiForceOneColumn: Boolean(values.multiForceOneColumn),
          // Task 24.3 fix: always present with a `null` fallback — see
          // core-node-converters.ts's header comment.
          localRef: localRefAttr(values.id) ?? null,
        },
        content: content.map((child) => ctx.block(child)),
      };
    }
    case "choiceList":
      return { type: "choiceList", content: content.map((child) => ctx.block(child)) };
    case "choiceItem":
      return { type: "choiceItem", content: content.map((child) => ctx.block(child)) };
    case "table": {
      // Task 24.3 fix: `attrs` (and every key inside it) is now
      // unconditionally present, matching the API's own mapper — see
      // core-node-converters.ts's header comment.
      return {
        type: "table",
        attrs: {
          caption: typeof values.caption === "string" ? values.caption : "",
          variant: values.variant !== undefined ? values.variant : "normal",
          align: values.align !== undefined ? values.align : "center",
          localRef: localRefAttr(values.id) ?? null,
        },
        content: content.map((child) => ctx.block(child)),
      };
    }
    case "tableRow":
      // Task 24.3 fix: `attrs` is now unconditionally present.
      return {
        type: "tableRow",
        attrs: { rowHeight: values.rowHeight ?? null },
        content: content.map((child) => ctx.block(child)),
      };
    case "tableHeader":
    case "tableCell":
      return {
        type: node.type,
        attrs: cellAttrsToSnapshot(node),
        content: content.map((child) => ctx.block(child)),
      };
    case "footnotes":
      return { type: "footnotes", content: content.map((child) => ctx.block(child)) };
    case "footnote":
      return {
        type: "footnote",
        attrs: { localRef: requiredString(values["data-id"], "footnote.data-id") },
        content: content.map((child) => ctx.block(child)),
      };
    case "crossRef":
      return {
        type: "crossRef",
        attrs: { targetRef: requiredString(values.targetId, "crossRef.targetId") },
      };
    case "footnoteReference":
      return {
        type: "footnoteReference",
        attrs: { targetRef: requiredString(values["data-id"], "footnoteReference.data-id") },
      };
    case "questionBlank":
      return {
        type: "questionBlank",
        attrs: { targetRef: requiredString(values.targetId, "questionBlank.targetId") },
      };
    case "inlineBlank":
      return { type: "inlineBlank" };
    default:
      return undefined;
  }
}

// --- Reverse: validated v2-shaped JSON -> Tiptap --------------------------

export function structuredNodeFromSnapshot(
  node: JSONContent,
  ctx: TiptapConversionContext,
): JSONContent | undefined {
  const content = node.content ?? [];
  const values = attrsOf(node);

  switch (node.type) {
    case "callout":
      return {
        type: "callout",
        attrs: {
          kind: values.kind,
          title: typeof values.title === "string" ? values.title : "",
          titleTouched: values.title !== null,
        },
        content: content.map((child) => ctx.block(child)),
      };
    case "proof":
      return { type: "proof", content: content.map((child) => ctx.block(child)) };
    case "question":
      return { type: "question", content: content.map((child) => ctx.block(child)) };
    case "questionItem":
      return {
        type: "questionItem",
        attrs: {
          kind: values.kind,
          writtenMode: values.writtenMode,
          writtenLines: values.writtenLines,
          writtenHeightPercent: values.writtenHeightPercent,
          writtenHeightCm: values.writtenHeightCm ?? null,
          multiForceOneColumn: Boolean(values.multiForceOneColumn),
          stashedChoiceJSON: null,
          id: typeof values.localRef === "string" ? values.localRef : null,
        },
        content: content.map((child) => ctx.block(child)),
      };
    case "choiceList":
      return { type: "choiceList", content: content.map((child) => ctx.block(child)) };
    case "choiceItem":
      return { type: "choiceItem", content: content.map((child) => ctx.block(child)) };
    case "table":
      return {
        type: "table",
        attrs: {
          caption: typeof values.caption === "string" ? values.caption : "",
          variant: typeof values.variant === "string" ? values.variant : "normal",
          align: typeof values.align === "string" ? values.align : "center",
          id: typeof values.localRef === "string" ? values.localRef : null,
        },
        content: content.map((child) => ctx.block(child)),
      };
    case "tableRow":
      return {
        type: "tableRow",
        attrs: { rowHeight: values.rowHeight ?? null },
        content: content.map((child) => ctx.block(child)),
      };
    case "tableHeader":
    case "tableCell":
      return {
        type: node.type,
        attrs: cellAttrsFromSnapshot(values),
        content: content.map((child) => ctx.block(child)),
      };
    case "footnotes":
      return { type: "footnotes", content: content.map((child) => ctx.block(child)) };
    case "footnote": {
      const localRef = requiredString(values.localRef, "footnote.localRef");
      return {
        type: "footnote",
        attrs: {
          // The real fn:N display id is recomputed by tiptap-footnotes'
          // own footnoteRules appendTransaction on the next transaction
          // that touches footnote references — this placeholder only
          // exists to satisfy the schema's `isRequired: true` (no default)
          // constraint, and is never meant to be read as meaningful data.
          id: localRef,
          "data-id": localRef,
        },
        content: content.map((child) => ctx.block(child)),
      };
    }
    case "crossRef":
      return {
        type: "crossRef",
        attrs: {
          targetId: values.targetRef,
          resolvedKind: null,
          resolvedValue: null,
          broken: false,
        },
      };
    case "footnoteReference":
      return {
        type: "footnoteReference",
        attrs: { "data-id": values.targetRef },
      };
    case "questionBlank":
      return {
        type: "questionBlank",
        attrs: { targetId: values.targetRef, resolvedValue: null, broken: false },
      };
    case "inlineBlank":
      return { type: "inlineBlank" };
    default:
      return undefined;
  }
}
